### PR TITLE
Des 505

### PR DESCRIPTION
**Pull request by mhomolak**
Port sync and webpack update

### CODE REVIEW

**Comment by wyseguyonline** [comment]
lgtm

**Comment by JasonLantz** [comment]
i just expanded the package.json and saw where you used the npm_scripts...

**Comment by mhomolak** [comment]
npm_scripts functions here as they do in component archetype.

I know we talked about normalizing the server start up.  Is this something we want to proceed with in all repos?

**Comment by JasonLantz** [comment]
probably the most urgent would be a component archtype update... that way consumers won't have the port problem.... but we should talk about what ports should be where... and if we need servers running concurrently ie elements running while compounds is running as well...

**Pull request merged**
